name: BlindChase
version: '${project.version}'
description: 'Play chase game within a blind'
main: pro.eng.yui.mcpl.blindChase.BlindChase
api-version: '1.20'

author: yui-KITAMURA

permissions:
  blindchase.*:
    default: op

commands:
  blindchase:
    description: BlindChase basic plugin commands
    aliases: 
      - blind
      - bc